title: Wenhao (Leon) Yi's Homepage
page-top-title: Wenhao (Leon) Yi
top-section-bg-text: Computer Science
home-subtitle: Wenhao (Leon) Yi&ensp;|&ensp;易文豪
copyright-text: '&copy; Wenhao Yi 2023-2026. All Rights Reserved.'
